### ISSUE TITLE
Modificacion de los archivos api.md y mecanismos_autenticacion_remota.md

### ISSUE THREAD

**Issue by ErickJPM** [ErickJPM/proyecto-matematicas#5]
@MariaFernandaReyesLopez por favor realiza lo siguiente:
En el archivo api.md investiga unas ventajas mas de las Apis de terceros y agrégalas debajo de las 3 escritas, con los respectivo números siguientes 4,5...etc.
En el archivo mecanismos_autenticacion_remota.md agrega un poco mas de información sobre lo que es un mecanismo de autenticación remota y agrégalo debajo de el párrafo superior y antes del subtitulo "Autenticación por token de sesión".

**Comment by MariaFernandaReyesLopez** [comment]
Ya he realizado lo solicitado. 👍
